# Change these first
owner: pal # Your GitHub organization or username, where this repository lives
repo: saas-template-upptime # The name of this repository

sites:
  - name: Peasy.nu
    url: https://www.peasy.nu
  - name: API Server
    url: https://saas-template.cool-runner-1.subtree.se/api/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /saas-template-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**saas-template** is a great system."
  introMessage: Any problems? Email us at [info@subtree.se](mailto:info@subtree.se).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
